---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
          - id: go-fmt
          - id: go-imports
          - id: go-unit-tests
          - id: go-build
          - id: go-mod-tidy
